#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const root = path.resolve(__dirname, "..");
const mappingPath = path.resolve(root, process.argv[2] || "redirects.json");
const pagesDirectory = path.join(root, "redirect-pages");
const redirectsOutput = path.join(root, "_redirects");
const generatedMarker = "<!-- Generated by scripts/generate_redirects.js. Do not edit. -->";
const redirectsMarker = "# Generated by scripts/generate_redirects.js. Do not edit.";

function normalizePath(value, label) {
  if (typeof value !== "string" || !value.startsWith("/") || value.startsWith("//")) {
    throw new Error(`${label} must be a site path starting with one slash.`);
  }

  if (/[?#\\\s]/.test(value)) {
    throw new Error(`${label} cannot contain a query, fragment, backslash, or whitespace.`);
  }

  let decoded;
  try {
    decoded = decodeURIComponent(value);
  } catch {
    throw new Error(`${label} contains invalid URL encoding.`);
  }

  if (decoded.split("/").some((segment) => segment === "." || segment === "..")) {
    throw new Error(`${label} cannot contain dot segments.`);
  }

  return value;
}

function routeKey(value) {
  let decoded = decodeURIComponent(value);
  decoded = decoded.replace(/\/+$/, "");
  return decoded || "/";
}

function loadExcludedPaths() {
  const configPath = path.join(root, "_config.yml");
  const lines = fs.readFileSync(configPath, "utf8").split(/\r?\n/);
  const excludedPaths = new Set();
  let inExcludeSection = false;

  for (const line of lines) {
    if (!inExcludeSection) {
      inExcludeSection = /^exclude:\s*$/.test(line);
      continue;
    }

    if (/^\S/.test(line)) break;
    const match = line.match(/^\s+-\s+(.+?)\s*$/);
    if (!match) continue;

    const value = match[1].replace(/^(["'])(.*)\1$/, "$2");
    excludedPaths.add(value.split(/[\\/]/).join(path.sep));
  }

  if (!inExcludeSection) {
    throw new Error("_config.yml does not define an exclude list.");
  }
  return excludedPaths;
}

function walkPageRoutes(directory, relativeDirectory = "", excludedPaths = new Set()) {
  const routes = new Set();
  if (!fs.existsSync(directory)) return routes;

  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if ([".git", "_site", "node_modules", "archive", "redirect-pages"].includes(entry.name)) continue;

    const absolutePath = path.join(directory, entry.name);
    const relativePath = path.join(relativeDirectory, entry.name);
    if (excludedPaths.has(relativePath)) continue;

    if (entry.isDirectory()) {
      for (const route of walkPageRoutes(absolutePath, relativePath, excludedPaths)) routes.add(route);
      continue;
    }

    if (!entry.isFile() || !/\.(html?|md|markdown)$/i.test(entry.name)) continue;
    if (relativePath.split(path.sep).includes("_posts")) continue;

    const withoutExtension = relativePath.replace(/\.(html?|md|markdown)$/i, "").split(path.sep).join("/");
    const isIndex = /(^|\/)index$/i.test(withoutExtension);
    const directoryRoute = withoutExtension.replace(/(^|\/)index$/i, "");
    const route = isIndex
      ? (directoryRoute ? `/${directoryRoute}/` : "/")
      : `/${withoutExtension}`;
    routes.add(routeKey(route));
  }

  return routes;
}

function escapeHtml(value) {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;"
  })[character]);
}

function loadRedirects() {
  const data = JSON.parse(fs.readFileSync(mappingPath, "utf8"));
  if (!data || !Array.isArray(data.redirects)) {
    throw new Error('Mapping file must contain a "redirects" array.');
  }

  const existingRoutes = walkPageRoutes(root, "", loadExcludedPaths());
  const seenSources = new Set();

  return data.redirects.map((redirect, index) => {
    const from = normalizePath(redirect.from, `redirects[${index}].from`);
    const to = redirect.to;
    const status = redirect.status ?? 301;

    if (typeof to !== "string" || !(to.startsWith("/") || /^https?:\/\//i.test(to))) {
      throw new Error(`redirects[${index}].to must be a site path or an HTTP(S) URL.`);
    }
    if (![301, 302, 307, 308].includes(status)) {
      throw new Error(`redirects[${index}].status must be 301, 302, 307, or 308.`);
    }
    if (to.startsWith("/") && routeKey(from) === routeKey(to)) {
      throw new Error(`redirects[${index}] redirects a path to itself.`);
    }

    const key = routeKey(from);
    if (seenSources.has(key)) throw new Error(`Duplicate redirect source: ${from}`);
    if (existingRoutes.has(key)) {
      throw new Error(`Redirect source ${from} already matches a page in the site.`);
    }
    seenSources.add(key);

    return { from, to, status };
  });
}

function redirectPage(redirect) {
  const permalink = `${redirect.from.replace(/\/$/, "")}/`;
  const safeTarget = escapeHtml(redirect.to);
  const scriptTarget = JSON.stringify(redirect.to).replace(/[<>&]/g, (character) => ({
    "<": "\\u003c",
    ">": "\\u003e",
    "&": "\\u0026"
  })[character]);
  return `---\npermalink: ${permalink}\n---\n${generatedMarker}\n<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="refresh" content="0; url=${safeTarget}">\n  <meta name="robots" content="noindex">\n  <title>Page moved</title>\n</head>\n<body>\n  <p>This page has moved. <a href="${safeTarget}">Continue to the new page</a>.</p>\n  <script>location.replace(${scriptTarget});</script>\n</body>\n</html>\n`;
}

function writeOutputs(redirects) {
  fs.mkdirSync(pagesDirectory, { recursive: true });
  const currentFiles = new Set();
  const rules = [];

  redirects.forEach((redirect) => {
    const id = crypto.createHash("sha256").update(routeKey(redirect.from)).digest("hex").slice(0, 16);
    const filePath = path.join(pagesDirectory, `redirect-${id}.html`);
    currentFiles.add(filePath);
    fs.writeFileSync(filePath, redirectPage(redirect));
    rules.push(`${redirect.from} ${redirect.to} ${redirect.status}`);
  });

  for (const name of fs.readdirSync(pagesDirectory)) {
    const filePath = path.join(pagesDirectory, name);
    if (!/^redirect-[a-f0-9]{16}\.html$/.test(name) || currentFiles.has(filePath)) continue;
    if (fs.readFileSync(filePath, "utf8").includes(generatedMarker)) fs.unlinkSync(filePath);
  }

  const generatedRules = `${rules.join("\n")}\n`;
  const output = `${redirectsMarker}\n${generatedRules}`;
  if (fs.existsSync(redirectsOutput)) {
    const existing = fs.readFileSync(redirectsOutput, "utf8");
    if (!existing.startsWith(`${redirectsMarker}\n`) && existing !== generatedRules) {
      throw new Error("_redirects already exists and is not generated by this script; refusing to overwrite it.");
    }
  }
  fs.writeFileSync(redirectsOutput, output);
  console.log(`Generated ${redirects.length} redirect(s) in _redirects and redirect-pages/.`);
}

try {
  writeOutputs(loadRedirects());
} catch (error) {
  console.error(`Redirect generation failed: ${error.message}`);
  process.exitCode = 1;
}